# create a user
POST http://localhost:4000/auth/register HTTP/1.1
Content-Type: application/json

{
  "name": "kanu",
  "email": "kenu@wos.kw",
  "password": "misuperpass"
}
###

# get token
POST http://localhost:4000/auth/login HTTP/1.1
Content-Type: application/json

{
  "email": "david@mo.mn",
  "password": "misuperpass"
}
###

# get profile
GET http://localhost:4000/auth/profile HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoiZGF2aWQiLCJlbWFpbCI6ImRhdmlkQG1vLm1uIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3MTQ5Mjg0NjQsImV4cCI6MTcxNTAxNDg2NH0.HZ-l1DsJPz_cf-dHvtsLv_EUiTEG3ADQa6zig26mbtc